import pandas as pd

def load_data(filename):
    """
    Load the data generated by our software.
    """
    return pd.read_csv(filename, sep=',', \
                       header=None, skiprows=1, \
                       names=['X', 'Y'])

